/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdjustColsListItem: typeof import('./src/components/AdjustColsListItem.vue')['default']
    ApiError: typeof import('./src/components/ApiError.vue')['default']
    CoreProductForm: typeof import('./src/components/forms/CoreProductForm.vue')['default']
    CoreProductTable: typeof import('./src/components/tables/CoreProductTable.vue')['default']
    DtFooter: typeof import('./src/components/DtFooter.vue')['default']
    FilterChip: typeof import('./src/components/FilterChip.vue')['default']
    FilterChipBool: typeof import('./src/components/FilterChipBool.vue')['default']
    FilterChipText: typeof import('./src/components/FilterChipText.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    LeftNavList: typeof import('./src/components/LeftNavList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
