
CREATE TABLE hr.employee
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address text_medium_mandatory,
  city text_medium_mandatory,
  country_fk bigint NOT NULL REFERENCES core.country(id),
  created_at tracking_at,
  created_by tracking_by,
  date_of_birth date NOT NULL CHECK (date_of_birth >= '1920-01-01'),
  family_name text_medium_mandatory,
  given_name text_medium_mandatory,
  hire_date date NOT NULL CHECK (hire_date >= '2010-01-01'),
  home_phone text_medium_mandatory,
  job_title text_medium_mandatory,
  last_user_update_by tracking_by,
  name text_medium_mandatory UNIQUE, -- not generated, in order to allow user to specify uniqueness however he chooses, e.g. using department or some other criterion
  notes varchar(2000) NOT NULL CHECK (notes != ''),
  postal_code text_short,
  reports_to_fk bigint REFERENCES hr.employee(id), -- self-reference - is made mandatory after data is inserted
  state text_short,
  title text_short_mandatory,
  updated_at tracking_at
);
COMMENT ON TABLE hr.employee IS 'shortname: emp';


CREATE TABLE hr.meeting_schedule
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  day core.weekday NOT NULL,
  frequency core.frequency NOT NULL,
  name text_medium_mandatory UNIQUE,
  scheduled_time time NOT NULL,
  updated_at tracking_at
);
COMMENT ON TABLE hr.meeting_schedule IS 'shortname: ms';
