
CREATE TABLE hr.employee
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address text NOT NULL,
  city text NOT NULL,
  country_fk bigint NOT NULL REFERENCES core.country(id),
  date_of_birth date NOT NULL CHECK (date_of_birth >= '1920-01-01'),
  entry_at tracking_at,
  entry_by tracking_by,
  first_name text NOT NULL,
  hire_date date NOT NULL CHECK (hire_date >= '2010-01-01'),
  home_phone text NOT NULL,
  job_title text NOT NULL,
  last_modified_at tracking_at,
  last_modified_by tracking_by,
  last_name text NOT NULL,
  name text NOT NULL UNIQUE, -- not generated, in order to allow user to specify uniqueness however he chooses, e.g. using department or some other criterion
  notes text NOT NULL,
  postal_code text NOT NULL,
  reports_to_fk bigint REFERENCES hr.employee(id), -- self-reference - is made mandatory after data is inserted
  state text NOT NULL,
  title text NOT NULL
);
COMMENT ON TABLE hr.employee IS 'shortname: hr_e';


CREATE TABLE hr.meeting_schedule
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day core.weekday NOT NULL,
  entry_at tracking_at,
  frequency core.frequency NOT NULL,
  last_modified_at tracking_at,
  name text NOT NULL UNIQUE,
  scheduled_time time NOT NULL
);
COMMENT ON TABLE hr.meeting_schedule IS 'shortname: hr_ms';
