
CREATE TABLE ecb.currency
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(3) NOT NULL UNIQUE CHECK (length(code) BETWEEN 2 AND 3), -- natural key
  created_at tracking_at,
  name varchar(500) NOT NULL CHECK (name != ''),
  updated_at tracking_at
);
COMMENT ON TABLE ecb.currency IS 'shortname: curr';


CREATE TABLE ecb.exchange_rate
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  day date NOT NULL,
  frequency ecb.frequency NOT NULL,
  from_currency_fk bigint NOT NULL REFERENCES ecb.currency(id),
  rate numeric(12,4) NOT NULL,
  to_currency_fk bigint NOT NULL REFERENCES ecb.currency(id),
  updated_at tracking_at,
  UNIQUE (frequency, day, from_currency_fk, to_currency_fk)
);
COMMENT ON TABLE ecb.exchange_rate IS 'shortname: xr';

CREATE INDEX exchange_rate_freq_day_idx ON ecb.exchange_rate USING btree(frequency, day);
CLUSTER ecb.exchange_rate USING exchange_rate_freq_day_idx;

