/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdjustColsListItem: typeof import('./src/components/AdjustColsListItem.vue')['default']
    ApiError: typeof import('./src/components/ApiError.vue')['default']
    CoreCategoryForm: typeof import('./src/components/forms/CoreCategoryForm.vue')['default']
    CoreCategoryTable: typeof import('./src/components/tables/CoreCategoryTable.vue')['default']
    CoreCountryForm: typeof import('./src/components/forms/CoreCountryForm.vue')['default']
    CoreCountryTable: typeof import('./src/components/tables/CoreCountryTable.vue')['default']
    CoreProductForm: typeof import('./src/components/forms/CoreProductForm.vue')['default']
    CoreProductTable: typeof import('./src/components/tables/CoreProductTable.vue')['default']
    CoreSupplierForm: typeof import('./src/components/forms/CoreSupplierForm.vue')['default']
    CoreSupplierTable: typeof import('./src/components/tables/CoreSupplierTable.vue')['default']
    DateTextField: typeof import('./src/components/DateTextField.vue')['default']
    DtFooter: typeof import('./src/components/DtFooter.vue')['default']
    FilterChip: typeof import('./src/components/FilterChip.vue')['default']
    FilterChipBool: typeof import('./src/components/FilterChipBool.vue')['default']
    FilterChipNumeric: typeof import('./src/components/FilterChipNumeric.vue')['default']
    FilterChipText: typeof import('./src/components/FilterChipText.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    HrEmployeeForm: typeof import('./src/components/forms/HrEmployeeForm.vue')['default']
    HrEmployeeTable: typeof import('./src/components/tables/HrEmployeeTable.vue')['default']
    HrMeetingScheduleForm: typeof import('./src/components/forms/HrMeetingScheduleForm.vue')['default']
    HrMeetingScheduleTable: typeof import('./src/components/tables/HrMeetingScheduleTable.vue')['default']
    LeftNavList: typeof import('./src/components/LeftNavList.vue')['default']
    RightNavList: typeof import('./src/components/RightNavList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesCustomerForm: typeof import('./src/components/forms/SalesCustomerForm.vue')['default']
    SalesCustomerTable: typeof import('./src/components/tables/SalesCustomerTable.vue')['default']
    SalesOrderForm: typeof import('./src/components/forms/SalesOrderForm.vue')['default']
    SalesOrderItemForm: typeof import('./src/components/forms/SalesOrderItemForm.vue')['default']
    SalesOrderItemTable: typeof import('./src/components/tables/SalesOrderItemTable.vue')['default']
    SalesOrderTable: typeof import('./src/components/tables/SalesOrderTable.vue')['default']
    SalesShipperForm: typeof import('./src/components/forms/SalesShipperForm.vue')['default']
    SalesShipperTable: typeof import('./src/components/tables/SalesShipperTable.vue')['default']
    SalesTerritoryForm: typeof import('./src/components/forms/SalesTerritoryForm.vue')['default']
    SalesTerritoryTable: typeof import('./src/components/tables/SalesTerritoryTable.vue')['default']
    TechPgBloatTable: typeof import('./src/components/tables/TechPgBloatTable.vue')['default']
    TechPgQueryTable: typeof import('./src/components/tables/TechPgQueryTable.vue')['default']
    TechPgSettingTable: typeof import('./src/components/tables/TechPgSettingTable.vue')['default']
    TechPgTableSizeTable: typeof import('./src/components/tables/TechPgTableSizeTable.vue')['default']
    TechPgUnusedIdxTable: typeof import('./src/components/tables/TechPgUnusedIdxTable.vue')['default']
    TimeTextField: typeof import('./src/components/TimeTextField.vue')['default']
  }
}
