
-- schemas and default privileges
-- new schemas also need to be added to config.toml

CREATE SCHEMA common AUTHORIZATION northwind_owner;

GRANT USAGE ON SCHEMA common TO northwind_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA common GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO northwind_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA common GRANT USAGE, SELECT ON SEQUENCES TO northwind_server;

GRANT USAGE ON SCHEMA common TO northwind_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA common GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO northwind_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA common GRANT USAGE, SELECT ON SEQUENCES TO northwind_cli;

----------------

CREATE SCHEMA core AUTHORIZATION northwind_owner;

GRANT USAGE ON SCHEMA core TO northwind_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO northwind_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT USAGE, SELECT ON SEQUENCES TO northwind_server;

GRANT USAGE ON SCHEMA core TO northwind_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO northwind_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT USAGE, SELECT ON SEQUENCES TO northwind_cli;

GRANT USAGE ON SCHEMA core TO nw_supplier;

----------------

CREATE SCHEMA ecb AUTHORIZATION northwind_owner;

GRANT USAGE ON SCHEMA ecb TO northwind_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO northwind_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT USAGE, SELECT ON SEQUENCES TO northwind_server;

GRANT USAGE ON SCHEMA ecb TO northwind_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO northwind_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT USAGE, SELECT ON SEQUENCES TO northwind_cli;

----------------

CREATE SCHEMA hr AUTHORIZATION northwind_owner;

GRANT USAGE ON SCHEMA hr TO northwind_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO northwind_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT USAGE, SELECT ON SEQUENCES TO northwind_server;

GRANT USAGE ON SCHEMA hr TO northwind_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO northwind_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT USAGE, SELECT ON SEQUENCES TO northwind_cli;

----------------

CREATE SCHEMA sales AUTHORIZATION northwind_owner;

GRANT USAGE ON SCHEMA sales TO northwind_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA sales GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO northwind_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA sales GRANT USAGE, SELECT ON SEQUENCES TO northwind_server;

GRANT USAGE ON SCHEMA hr TO northwind_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO northwind_cli;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT USAGE, SELECT ON SEQUENCES TO northwind_cli;

----------------

CREATE SCHEMA system AUTHORIZATION northwind_owner;

GRANT USAGE ON SCHEMA system TO northwind_server;
GRANT USAGE ON SCHEMA system TO northwind_cli;
