
INSERT INTO core.category (id, name, description, color_hex, color_is_light) VALUES (-1, 'None', 'None', '', false);
INSERT INTO core.category (name, description, color_hex, color_is_light) VALUES
  ('Beverages','Soft drinks, coffees, teas, beers, and ales', '', false),
  ('Condiments','Sweet and savory sauces, relishes, spreads, and seasonings', '', false),
  ('Confections','Desserts, candies, and sweet breads', '', false),
  ('Dairy Products','Cheeses', '', false),
  ('Grains/Cereals','Breads, crackers, pasta, and cereal', '', false),
  ('Meat/Poultry','Prepared meats', '', false),
  ('Produce','Dried fruit and bean curd', '', false),
  ('Seafood','Seaweed and fish', '', false),
  ('Test category','Test', '', false);


INSERT INTO core.supplier (company_name, contact_name, contact_title, address, city, state, postal_code, phone, country_fk) VALUES
  ('G''day, Mate','Wendy Mackenzie','Sales Representative','170 Prince Edward Parade Hunter''s Hill','Sydney','NSW','2042','(02) 555-5914',(SELECT id FROM common.country WHERE iso2 = 'AU')),
  ('Formaggi Fortini s.r.l.','Elio Rossi','Sales Representative','Viale Dante, 75','Ravenna','','48100','(0544) 60323',(SELECT id FROM common.country WHERE iso2 = 'IT')),
  ('Specialty Biscuits, Ltd.','Peter Wilson','Sales Representative','29 King''s Way','Manchester','','M14 GSD','(161) 555-4448',(SELECT id FROM common.country WHERE iso2 = 'UK')),
  ('Refrescos Americanas LTDA','Carlos Diaz','Marketing Manager','Av. das Americanas 12.890','Sao Paulo','','5442','(11) 555 4640',(SELECT id FROM common.country WHERE iso2 = 'BR')),
  ('Heli Süßwaren GmbH & Co. KG','Petra Winkler','Sales Manager','Tiergartenstraße 5','Berlin','','10785','(010) 9984510',(SELECT id FROM common.country WHERE iso2 = 'DE')),
  ('Norske Meierier','Beate Vileid','Marketing Manager','Hatlevegen 5','Sandvika','','1320','(0)2-953010',(SELECT id FROM common.country WHERE iso2 = 'NO')),
  ('Svensk Sjöföda AB','Michael Björn','Sales Representative','Brovallavägen 231','Stockholm','','S-123 45','08-123 45 67',(SELECT id FROM common.country WHERE iso2 = 'SE')),
  ('Leka Trading','Chandra Leka','Owner','471 Serangoon Loop, Suite #402','Singapore','','512','555-8787',(SELECT id FROM common.country WHERE iso2 = 'SG')),
  ('Karkki Oy','Anne Heikkonen','Product Manager','Valtakatu 12','Lappeenranta','','53120','(953) 10956',(SELECT id FROM common.country WHERE iso2 = 'FI')),
  ('Escargots Nouveaux','Marie Delamare','Sales Manager','22, rue H. Voiron','Montceau','','71300','85.57.00.07',(SELECT id FROM common.country WHERE iso2 = 'FR')),
  ('New Orleans Cajun Delights','Shelley Burke','Order Administrator','P.O. Box 78934','New Orleans','LA','70117','(100) 555-4822',(SELECT id FROM common.country WHERE iso2 = 'US')),
  ('Mayumi''s','Mayumi Ohno','Marketing Representative','92 Setsuko Chuo-ku','Osaka','','545','(06) 431-7877',(SELECT id FROM common.country WHERE iso2 = 'JP')),
  ('Plutzer Lebensmittelgroßmärkte AG','Martin Bein','International Marketing Mgr.','Bogenallee 51','Frankfurt','','60439','(069) 992755',(SELECT id FROM common.country WHERE iso2 = 'DE')),
  ('Grandma Kelly''s Homestead','Regina Murphy','Sales Representative','707 Oxford Rd.','Ann Arbor','MI','48104','(313) 555-5735',(SELECT id FROM common.country WHERE iso2 = 'US')),
  ('Pavlova, Ltd.','Ian Devling','Marketing Manager','74 Rose St. Moonie Ponds','Melbourne','Victoria','3058','(03) 444-2343',(SELECT id FROM common.country WHERE iso2 = 'AU')),
  ('New England Seafood Cannery','Robb Merchant','Wholesale Account Agent','Order Processing Dept. 2100 Paul Revere Blvd.','Boston','MA','2134','(617) 555-3267',(SELECT id FROM common.country WHERE iso2 = 'US')),
  ('Forêts d''érables','Chantal Goulet','Accounting Manager','148 rue Chasseur','Ste-Hyacinthe','Québec','J2S 7S8','(514) 555-2955',(SELECT id FROM common.country WHERE iso2 = 'CA')),
  ('PB Knäckebröd AB','Lars Peterson','Sales Agent','Kaloadagatan 13','Göteborg','','S-345 67','031-987 65 43',(SELECT id FROM common.country WHERE iso2 = 'SE')),
  ('Nord-Ost-Fisch Handelsgesellschaft mbH','Sven Petersen','Coordinator Foreign Markets','Frahmredder 112a','Cuxhaven','','27478','(04721) 8713',(SELECT id FROM common.country WHERE iso2 = 'DE')),
  ('Aux joyeux ecclésiastiques','Guylène Nodier','Sales Manager','203, Rue des Francs-Bourgeois','Paris','','75004','(1) 03.83.00.68',(SELECT id FROM common.country WHERE iso2 = 'FR')),
  ('Lyngbysild','Niels Petersen','Sales Manager','Lyngbysild Fiskebakken 10','Lyngby','','2800','43844108',(SELECT id FROM common.country WHERE iso2 = 'DK')),
  ('Zaanse Snoepfabriek','Dirk Luchte','Accounting Manager','Verkoop Rijnweg 22','Zaandam','','9999 ZZ','(12345) 1212',(SELECT id FROM common.country WHERE iso2 = 'NL')),
  ('Pasta Buttini s.r.l.','Giovanni Giudici','Order Administrator','Via dei Gelsomini, 153','Salerno','','84100','(089) 6547665',(SELECT id FROM common.country WHERE iso2 = 'IT')),
  ('Gai pâturage','Eliane Noz','Sales Representative','Bat. B 3, rue des Alpes','Annecy','','74000','38.76.98.06',(SELECT id FROM common.country WHERE iso2 = 'FR')),
  ('Cooperativa de Quesos ''Las Cabras''','Antonio del Valle Saavedra','Export Administrator','Calle del Rosal 4','Oviedo','Asturias','33007','(98) 598 76 54',(SELECT id FROM common.country WHERE iso2 = 'ES')),
  ('Bigfoot Breweries','Cheryl Saylor','Regional Account Rep.','3400 - 8th Avenue Suite 210','Bend','OR','97101','(503) 555-9931',(SELECT id FROM common.country WHERE iso2 = 'US')),
  ('Ma Maison','Jean-Guy Lauzon','Marketing Manager','2960 Rue St. Laurent','Montréal','Québec','H1J 1C3','(514) 555-9022',(SELECT id FROM common.country WHERE iso2 = 'CA')),
  ('Exotic Liquids','Charlotte Cooper','Purchasing Manager','49 Gilbert St.','London','','EC1 4SD','(171) 555-2222',(SELECT id FROM common.country WHERE iso2 = 'UK')),
  ('Tokyo Traders','Yoshi Nagase','Marketing Manager','9-8 Sekimai Musashino-shi','Tokyo','','100','(03) 3555-5011',(SELECT id FROM common.country WHERE iso2 = 'JP'));

-- update active countries
UPDATE common.country SET is_active = true WHERE id IN (SELECT DISTINCT country_fk FROM core.supplier);

INSERT INTO core.product (name, supplier_fk, category_fk, quantity_per_unit, unit_price, units_in_stock, units_on_order, reorder_level, is_discontinued, tags) VALUES
  ('Chai',(SELECT id FROM core.supplier WHERE company_name = 'Specialty Biscuits, Ltd.'),(SELECT id FROM core.category WHERE name = 'Beverages'),'10 boxes x 30 bags',18,39,0,10,TRUE,'{health}'),
  ('Chang',(SELECT id FROM core.supplier WHERE company_name = 'Exotic Liquids'),(SELECT id FROM core.category WHERE name = 'Beverages'),'24 - 12 oz bottles',19,17,40,25,TRUE,'{new age,trendy}'),
  ('Chef Anton''s Gumbo Mix',(SELECT id FROM core.supplier WHERE company_name = 'New Orleans Cajun Delights'),(SELECT id FROM core.category WHERE name = 'Condiments'),'36 boxes',21.35,0,0,0,TRUE,'{}'),
  ('Mishi Kobe Niku',(SELECT id FROM core.supplier WHERE company_name = 'Tokyo Traders'),(SELECT id FROM core.category WHERE name = 'Meat/Poultry'),'18 - 500 g pkgs.',97,29,0,0,TRUE,'{}'),
  ('Alice Mutton',(SELECT id FROM core.supplier WHERE company_name = 'Pavlova, Ltd.'),(SELECT id FROM core.category WHERE name = 'Meat/Poultry'),'20 - 1 kg tins',39,0,0,0,TRUE,'{}'),
  ('Guaraná Fantástica',(SELECT id FROM core.supplier WHERE company_name = 'Refrescos Americanas LTDA'),(SELECT id FROM core.category WHERE name = 'Beverages'),'12 - 355 ml cans',4.5,20,0,0,TRUE,'{}'),
  ('Rössle Sauerkraut',(SELECT id FROM core.supplier WHERE company_name = 'Plutzer Lebensmittelgroßmärkte AG'),(SELECT id FROM core.category WHERE name = 'Produce'),'25 - 825 g cans',45.6,26,0,0,TRUE,'{}'),
  ('Thüringer Rostbratwurst',(SELECT id FROM core.supplier WHERE company_name = 'Plutzer Lebensmittelgroßmärkte AG'),(SELECT id FROM core.category WHERE name = 'Meat/Poultry'),'50 bags x 30 sausgs.',123.79,0,0,0,TRUE,'{}'),
  ('Singaporean Hokkien Fried Mee',(SELECT id FROM core.supplier WHERE company_name = 'Leka Trading'),(SELECT id FROM core.category WHERE name = 'Grains/Cereals'),'32 - 1 kg pkgs.',14,26,0,0,TRUE,'{}'),
  ('Perth Pasties',(SELECT id FROM core.supplier WHERE company_name = 'G''day, Mate'),(SELECT id FROM core.category WHERE name = 'Meat/Poultry'),'48 pieces',32.8,0,0,0,TRUE,'{}'),
  ('Aniseed Syrup',(SELECT id FROM core.supplier WHERE company_name = 'Exotic Liquids'),(SELECT id FROM core.category WHERE name = 'Condiments'),'12 - 550 ml bottles',10,13,70,25,FALSE,'{}'),
  ('Chef Anton''s Cajun Seasoning',(SELECT id FROM core.supplier WHERE company_name = 'New Orleans Cajun Delights'),(SELECT id FROM core.category WHERE name = 'Condiments'),'48 - 6 oz jars',22,53,0,0,FALSE,'{}'),
  ('Grandma''s Boysenberry Spread',(SELECT id FROM core.supplier WHERE company_name = 'Grandma Kelly''s Homestead'),(SELECT id FROM core.category WHERE name = 'Condiments'),'12 - 8 oz jars',25,120,0,25,FALSE,'{}'),
  ('Uncle Bob''s Organic Dried Pears',(SELECT id FROM core.supplier WHERE company_name = 'Grandma Kelly''s Homestead'),(SELECT id FROM core.category WHERE name = 'Produce'),'12 - 1 lb pkgs.',30,15,0,10,FALSE,'{}'),
  ('Northwoods Cranberry Sauce',(SELECT id FROM core.supplier WHERE company_name = 'Grandma Kelly''s Homestead'),(SELECT id FROM core.category WHERE name = 'Condiments'),'12 - 12 oz jars',40,6,0,0,FALSE,'{}'),
  ('Ikura',(SELECT id FROM core.supplier WHERE company_name = 'Tokyo Traders'),(SELECT id FROM core.category WHERE name = 'Seafood'),'12 - 200 ml jars',31,31,0,0,FALSE,'{}'),
  ('Queso Cabrales',(SELECT id FROM core.supplier WHERE company_name = 'Cooperativa de Quesos ''Las Cabras'''),(SELECT id FROM core.category WHERE name = 'Dairy Products'),'1 kg pkg.',21,22,30,30,FALSE,'{}'),
  ('Queso Manchego La Pastora',(SELECT id FROM core.supplier WHERE company_name = 'Cooperativa de Quesos ''Las Cabras'''),(SELECT id FROM core.category WHERE name = 'Dairy Products'),'10 - 500 g pkgs.',38,86,0,0,FALSE,'{}'),
  ('Konbu',(SELECT id FROM core.supplier WHERE company_name = 'Mayumi''s'),(SELECT id FROM core.category WHERE name = 'Seafood'),'2 kg box',6,24,0,5,FALSE,'{}'),
  ('Tofu',(SELECT id FROM core.supplier WHERE company_name = 'Mayumi''s'),(SELECT id FROM core.category WHERE name = 'Produce'),'40 - 100 g pkgs.',23.25,35,0,0,FALSE,'{}'),
  ('Genen Shouyu',(SELECT id FROM core.supplier WHERE company_name = 'Mayumi''s'),(SELECT id FROM core.category WHERE name = 'Condiments'),'24 - 250 ml bottles',13,39,0,5,FALSE,'{}'),
  ('Pavlova',(SELECT id FROM core.supplier WHERE company_name = 'Pavlova, Ltd.'),(SELECT id FROM core.category WHERE name = 'Confections'),'32 - 500 g boxes',17.45,29,0,10,FALSE,'{}'),
  ('Carnarvon Tigers',(SELECT id FROM core.supplier WHERE company_name = 'Pavlova, Ltd.'),(SELECT id FROM core.category WHERE name = 'Seafood'),'16 kg pkg.',62.5,42,0,0,FALSE,'{}'),
  ('Teatime Chocolate Biscuits',(SELECT id FROM core.supplier WHERE company_name = 'Specialty Biscuits, Ltd.'),(SELECT id FROM core.category WHERE name = 'Confections'),'10 boxes x 12 pieces',9.2,25,0,5,FALSE,'{}'),
  ('Sir Rodney''s Marmalade',(SELECT id FROM core.supplier WHERE company_name = 'Specialty Biscuits, Ltd.'),(SELECT id FROM core.category WHERE name = 'Confections'),'30 gift boxes',81,40,0,0,FALSE,'{}'),
  ('Sir Rodney''s Scones',(SELECT id FROM core.supplier WHERE company_name = 'Specialty Biscuits, Ltd.'),(SELECT id FROM core.category WHERE name = 'Confections'),'24 pkgs. x 4 pieces',10,3,40,5,FALSE,'{}'),
  ('Gustaf''s Knäckebröd',(SELECT id FROM core.supplier WHERE company_name = 'PB Knäckebröd AB'),(SELECT id FROM core.category WHERE name = 'Grains/Cereals'),'24 - 500 g pkgs.',21,104,0,25,FALSE,'{}'),
  ('Tunnbröd',(SELECT id FROM core.supplier WHERE company_name = 'PB Knäckebröd AB'),(SELECT id FROM core.category WHERE name = 'Grains/Cereals'),'12 - 250 g pkgs.',9,61,0,25,FALSE,'{}'),
  ('NuNuCa Nuß-Nougat-Creme',(SELECT id FROM core.supplier WHERE company_name = 'Heli Süßwaren GmbH & Co. KG'),(SELECT id FROM core.category WHERE name = 'Confections'),'20 - 450 g glasses',14,76,0,30,FALSE,'{}'),
  ('Gumbär Gummibärchen',(SELECT id FROM core.supplier WHERE company_name = 'Heli Süßwaren GmbH & Co. KG'),(SELECT id FROM core.category WHERE name = 'Confections'),'100 - 250 g bags',31.23,15,0,0,FALSE,'{}'),
  ('Schoggi Schokolade',(SELECT id FROM core.supplier WHERE company_name = 'Heli Süßwaren GmbH & Co. KG'),(SELECT id FROM core.category WHERE name = 'Confections'),'100 - 100 g pieces',43.9,49,0,30,FALSE,'{}'),
  ('Nord-Ost Matjeshering',(SELECT id FROM core.supplier WHERE company_name = 'Nord-Ost-Fisch Handelsgesellschaft mbH'),(SELECT id FROM core.category WHERE name = 'Seafood'),'10 - 200 g glasses',25.89,10,0,15,FALSE,'{}'),
  ('Gorgonzola Telino',(SELECT id FROM core.supplier WHERE company_name = 'Formaggi Fortini s.r.l.'),(SELECT id FROM core.category WHERE name = 'Dairy Products'),'12 - 100 g pkgs',12.5,0,70,20,FALSE,'{}'),
  ('Mascarpone Fabioli',(SELECT id FROM core.supplier WHERE company_name = 'Formaggi Fortini s.r.l.'),(SELECT id FROM core.category WHERE name = 'Dairy Products'),'24 - 200 g pkgs.',32,9,40,25,FALSE,'{}'),
  ('Geitost',(SELECT id FROM core.supplier WHERE company_name = 'Norske Meierier'),(SELECT id FROM core.category WHERE name = 'Dairy Products'),'500 g',2.5,112,0,20,FALSE,'{}'),
  ('Sasquatch Ale',(SELECT id FROM core.supplier WHERE company_name = 'Bigfoot Breweries'),(SELECT id FROM core.category WHERE name = 'Beverages'),'24 - 12 oz bottles',14,111,0,15,FALSE,'{}'),
  ('Steeleye Stout',(SELECT id FROM core.supplier WHERE company_name = 'Bigfoot Breweries'),(SELECT id FROM core.category WHERE name = 'Beverages'),'24 - 12 oz bottles',18,20,0,15,FALSE,'{}'),
  ('Inlagd Sill',(SELECT id FROM core.supplier WHERE company_name = 'Svensk Sjöföda AB'),(SELECT id FROM core.category WHERE name = 'Seafood'),'24 - 250 g  jars',19,112,0,20,FALSE,'{}'),
  ('Gravad lax',(SELECT id FROM core.supplier WHERE company_name = 'Svensk Sjöföda AB'),(SELECT id FROM core.category WHERE name = 'Seafood'),'12 - 500 g pkgs.',26,11,50,25,FALSE,'{}'),
  ('Côte de Blaye',(SELECT id FROM core.supplier WHERE company_name = 'Aux joyeux ecclésiastiques'),(SELECT id FROM core.category WHERE name = 'Beverages'),'12 - 75 cl bottles',263.5,17,0,15,FALSE,'{}'),
  ('Chartreuse verte',(SELECT id FROM core.supplier WHERE company_name = 'Aux joyeux ecclésiastiques'),(SELECT id FROM core.category WHERE name = 'Beverages'),'750 cc per bottle',18,69,0,5,FALSE,'{}'),
  ('Boston Crab Meat',(SELECT id FROM core.supplier WHERE company_name = 'New England Seafood Cannery'),(SELECT id FROM core.category WHERE name = 'Seafood'),'24 - 4 oz tins',18.4,123,0,30,FALSE,'{}'),
  ('Jack''s New England Clam Chowder',(SELECT id FROM core.supplier WHERE company_name = 'New England Seafood Cannery'),(SELECT id FROM core.category WHERE name = 'Seafood'),'12 - 12 oz cans',9.65,85,0,10,FALSE,'{}'),
  ('Ipoh Coffee',(SELECT id FROM core.supplier WHERE company_name = 'Leka Trading'),(SELECT id FROM core.category WHERE name = 'Beverages'),'16 - 500 g tins',46,17,10,25,FALSE,'{}'),
  ('Gula Malacca',(SELECT id FROM core.supplier WHERE company_name = 'Leka Trading'),(SELECT id FROM core.category WHERE name = 'Condiments'),'20 - 2 kg bags',19.45,27,0,15,FALSE,'{}'),
  ('Rogede sild',(SELECT id FROM core.supplier WHERE company_name = 'Lyngbysild'),(SELECT id FROM core.category WHERE name = 'Seafood'),'1k pkg.',9.5,5,70,15,FALSE,'{}'),
  ('Spegesild',(SELECT id FROM core.supplier WHERE company_name = 'Lyngbysild'),(SELECT id FROM core.category WHERE name = 'Seafood'),'4 - 450 g glasses',12,95,0,0,FALSE,'{}'),
  ('Zaanse koeken',(SELECT id FROM core.supplier WHERE company_name = 'Zaanse Snoepfabriek'),(SELECT id FROM core.category WHERE name = 'Confections'),'10 - 4 oz boxes',9.5,36,0,0,FALSE,'{}'),
  ('Chocolade',(SELECT id FROM core.supplier WHERE company_name = 'Zaanse Snoepfabriek'),(SELECT id FROM core.category WHERE name = 'Confections'),'10 pkgs.',12.75,15,70,25,FALSE,'{}'),
  ('Maxilaku',(SELECT id FROM core.supplier WHERE company_name = 'Karkki Oy'),(SELECT id FROM core.category WHERE name = 'Confections'),'24 - 50 g pkgs.',20,10,60,15,FALSE,'{}'),
  ('Valkoinen suklaa',(SELECT id FROM core.supplier WHERE company_name = 'Karkki Oy'),(SELECT id FROM core.category WHERE name = 'Confections'),'12 - 100 g bars',16.25,65,0,30,FALSE,'{}'),
  ('Manjimup Dried Apples',(SELECT id FROM core.supplier WHERE company_name = 'G''day, Mate'),(SELECT id FROM core.category WHERE name = 'Produce'),'50 - 300 g pkgs.',53,20,0,10,FALSE,'{}'),
  ('Filo Mix',(SELECT id FROM core.supplier WHERE company_name = 'G''day, Mate'),(SELECT id FROM core.category WHERE name = 'Grains/Cereals'),'16 - 2 kg boxes',7,38,0,25,FALSE,'{}'),
  ('Tourtière',(SELECT id FROM core.supplier WHERE company_name = 'Ma Maison'),(SELECT id FROM core.category WHERE name = 'Meat/Poultry'),'16 pies',7.45,21,0,10,FALSE,'{}'),
  ('Pâté chinois',(SELECT id FROM core.supplier WHERE company_name = 'Ma Maison'),(SELECT id FROM core.category WHERE name = 'Meat/Poultry'),'24 boxes x 2 pies',24,115,0,20,FALSE,'{}'),
  ('Gnocchi di nonna Alice',(SELECT id FROM core.supplier WHERE company_name = 'Pasta Buttini s.r.l.'),(SELECT id FROM core.category WHERE name = 'Grains/Cereals'),'24 - 250 g pkgs.',38,21,10,30,FALSE,'{}'),
  ('Ravioli Angelo',(SELECT id FROM core.supplier WHERE company_name = 'Pasta Buttini s.r.l.'),(SELECT id FROM core.category WHERE name = 'Grains/Cereals'),'24 - 250 g pkgs.',19.5,36,0,20,FALSE,'{}'),
  ('Escargots de Bourgogne',(SELECT id FROM core.supplier WHERE company_name = 'Escargots Nouveaux'),(SELECT id FROM core.category WHERE name = 'Seafood'),'24 pieces',13.25,62,0,20,FALSE,'{}'),
  ('Raclette Courdavault',(SELECT id FROM core.supplier WHERE company_name = 'Gai pâturage'),(SELECT id FROM core.category WHERE name = 'Dairy Products'),'5 kg pkg.',55,79,0,0,FALSE,'{}'),
  ('Camembert Pierrot',(SELECT id FROM core.supplier WHERE company_name = 'Gai pâturage'),(SELECT id FROM core.category WHERE name = 'Dairy Products'),'15 - 300 g rounds',34,19,0,0,FALSE,'{}'),
  ('Sirop d''érable',(SELECT id FROM core.supplier WHERE company_name = 'Forêts d''érables'),(SELECT id FROM core.category WHERE name = 'Condiments'),'24 - 500 ml bottles',28.5,113,0,25,FALSE,'{}'),
  ('Tarte au sucre',(SELECT id FROM core.supplier WHERE company_name = 'Forêts d''érables'),(SELECT id FROM core.category WHERE name = 'Confections'),'48 pies',49.3,17,0,0,FALSE,'{}'),
  ('Vegie-spread',(SELECT id FROM core.supplier WHERE company_name = 'Pavlova, Ltd.'),(SELECT id FROM core.category WHERE name = 'Condiments'),'15 - 625 g jars',43.9,24,0,5,FALSE,'{}'),
  ('Wimmers gute Semmelknödel',(SELECT id FROM core.supplier WHERE company_name = 'Plutzer Lebensmittelgroßmärkte AG'),(SELECT id FROM core.category WHERE name = 'Grains/Cereals'),'20 bags x 4 pieces',33.25,22,80,30,FALSE,'{}'),
  ('Louisiana Fiery Hot Pepper Sauce',(SELECT id FROM core.supplier WHERE company_name = 'New Orleans Cajun Delights'),(SELECT id FROM core.category WHERE name = 'Condiments'),'32 - 8 oz bottles',21.05,76,0,0,FALSE,'{}'),
  ('Louisiana Hot Spiced Okra',(SELECT id FROM core.supplier WHERE company_name = 'New Orleans Cajun Delights'),(SELECT id FROM core.category WHERE name = 'Condiments'),'24 - 8 oz jars',17,4,100,20,FALSE,'{}'),
  ('Laughing Lumberjack Lager',(SELECT id FROM core.supplier WHERE company_name = 'Bigfoot Breweries'),(SELECT id FROM core.category WHERE name = 'Beverages'),'24 - 12 oz bottles',14,52,0,10,FALSE,'{}'),
  ('Scottish Longbreads',(SELECT id FROM core.supplier WHERE company_name = 'Specialty Biscuits, Ltd.'),(SELECT id FROM core.category WHERE name = 'Confections'),'10 boxes x 8 pieces',12.5,6,10,15,FALSE,'{}'),
  ('Gudbrandsdalsost',(SELECT id FROM core.supplier WHERE company_name = 'Norske Meierier'),(SELECT id FROM core.category WHERE name = 'Dairy Products'),'10 kg pkg.',36,26,0,15,FALSE,'{}'),
  ('Outback Lager',(SELECT id FROM core.supplier WHERE company_name = 'Pavlova, Ltd.'),(SELECT id FROM core.category WHERE name = 'Beverages'),'24 - 355 ml bottles',15,15,10,30,FALSE,'{}'),
  ('Flotemysost',(SELECT id FROM core.supplier WHERE company_name = 'Norske Meierier'),(SELECT id FROM core.category WHERE name = 'Dairy Products'),'10 - 500 g pkgs.',21.5,26,0,0,FALSE,'{}'),
  ('Mozzarella di Giovanni',(SELECT id FROM core.supplier WHERE company_name = 'Formaggi Fortini s.r.l.'),(SELECT id FROM core.category WHERE name = 'Dairy Products'),'24 - 200 g pkgs.',34.8,14,0,0,FALSE,'{}'),
  ('Röd Kaviar',(SELECT id FROM core.supplier WHERE company_name = 'Svensk Sjöföda AB'),(SELECT id FROM core.category WHERE name = 'Seafood'),'24 - 150 g jars',15,101,0,5,FALSE,'{}'),
  ('Longlife Tofu',(SELECT id FROM core.supplier WHERE company_name = 'Tokyo Traders'),(SELECT id FROM core.category WHERE name = 'Produce'),'5 kg pkg.',10,4,20,5,FALSE,'{}'),
  ('Rhönbräu Klosterbier',(SELECT id FROM core.supplier WHERE company_name = 'Plutzer Lebensmittelgroßmärkte AG'),(SELECT id FROM core.category WHERE name = 'Beverages'),'24 - 0.5 l bottles',7.75,125,0,25,FALSE,'{}'),
  ('Lakkalikööri',(SELECT id FROM core.supplier WHERE company_name = 'Karkki Oy'),(SELECT id FROM core.category WHERE name = 'Beverages'),'500 ml',18,57,0,20,FALSE,'{}'),
  ('Original Frankfurter grüne Soße',(SELECT id FROM core.supplier WHERE company_name = 'Plutzer Lebensmittelgroßmärkte AG'),(SELECT id FROM core.category WHERE name = 'Condiments'),'12 boxes',13,32,0,15,FALSE,'{}');
