
CREATE TABLE core.category
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  color_hex varchar(7) NOT NULL,
  color_is_light boolean NOT NULL,
  created_at tracking_at,
  created_by tracking_by,
  description text_medium_mandatory UNIQUE,
  last_user_update_by tracking_by,
  name text_short_mandatory UNIQUE,
  updated_at tracking_at
);
COMMENT ON TABLE core.category IS 'shortname: cat';
GRANT SELECT ON core.category TO nw_supplier;


CREATE TABLE core.country
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  created_by tracking_by,
  is_active boolean NOT NULL DEFAULT false,
  iso2 char(2) NOT NULL UNIQUE CHECK (iso2 ~ '^[A-Z]+$'), -- ~ for case sensitive match, ^ and $ to to match whole string
  name text_short_mandatory UNIQUE,
  updated_at tracking_at
);
COMMENT ON TABLE core.country IS 'shortname: co';
GRANT SELECT ON core.country TO nw_supplier;


CREATE TABLE core.supplier
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address text_medium,
  city text_medium,
  company_name text_medium_mandatory,
  contact_name text_medium_mandatory,
  contact_title text_short,
  country_fk bigint NOT NULL REFERENCES core.country (id),
  created_at tracking_at,
  created_by tracking_by,
  last_user_update_by tracking_by,
  phone text_short,
  postal_code text_short,
  state text_short,
  updated_at tracking_at,
  UNIQUE (country_fk, company_name)
);
COMMENT ON TABLE core.supplier IS 'shortname: s';
GRANT SELECT ON core.supplier TO nw_supplier;


CREATE TABLE core.product
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_fk bigint NOT NULL REFERENCES core.category (id),
  created_at tracking_at,
  created_by tracking_by,
  is_discontinued boolean NOT NULL,
  last_user_update_by tracking_by,
  name text_medium_mandatory UNIQUE,
  quantity_per_unit text_short_mandatory,
  reorder_level int_gte0,
  supplier_fk bigint NOT NULL REFERENCES core.supplier (id),
  tags text[] NOT NULL DEFAULT '{}',
  unit_price price_gte0,
  units_in_stock int_gte0,
  units_on_order int_gte0,
  updated_at tracking_at
);
COMMENT ON TABLE core.product IS 'shortname: p';
GRANT ALL ON core.product TO nw_supplier;

--RLS
ALTER TABLE core.product ENABLE ROW LEVEL SECURITY;

-- allow backoffice roles to bypass RLS
CREATE POLICY northwind_owner_all ON core.product TO northwind_owner USING (true) WITH CHECK (true);
CREATE POLICY northwind_server_all ON core.product TO northwind_server USING (true) WITH CHECK (true);
CREATE POLICY northwind_cli_all ON core.product TO northwind_cli USING (true) WITH CHECK (true);

-- enforce RLS for supplier role
CREATE POLICY nw_supplier_self_only ON core.product TO nw_supplier USING (supplier_fk = current_setting('app.supplier_id')::bigint);