
CREATE TABLE core.category
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  color_hex text NOT NULL,
  color_is_light boolean NOT NULL,
  created_at tracking_at,
  created_by tracking_by,
  description text NOT NULL UNIQUE,
  last_user_update_by tracking_by,
  name text NOT NULL UNIQUE,
  updated_at tracking_at
);
COMMENT ON TABLE core.category IS 'shortname: cat';


CREATE TABLE core.country
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  created_by tracking_by,
  is_active bool NOT NULL DEFAULT false,
  iso2 text NOT NULL UNIQUE,
  name text NOT NULL UNIQUE,
  updated_at tracking_at,
  CONSTRAINT co_iso2_len CHECK (char_length(iso2) = 2)
);
COMMENT ON TABLE core.country IS 'shortname: co';


CREATE TABLE core.supplier
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address text NOT NULL,
  city text NOT NULL,
  company_name text NOT NULL,
  contact_name text NOT NULL,
  contact_title text NOT NULL,
  country_fk bigint NOT NULL REFERENCES core.country (id),
  created_at tracking_at,
  created_by tracking_by,
  last_user_update_by tracking_by,
  phone text NOT NULL,
  postal_code text NOT NULL,
  state text NOT NULL,
  updated_at tracking_at,
  UNIQUE (country_fk, company_name)
);
COMMENT ON TABLE core.supplier IS 'shortname: s';


CREATE TABLE core.product
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_fk bigint NOT NULL REFERENCES core.category (id),
  created_at tracking_at,
  created_by tracking_by,
  is_discontinued boolean NOT NULL,
  last_user_update_by tracking_by,
  name text NOT NULL UNIQUE,
  quantity_per_unit text NOT NULL,
  reorder_level integer NOT NULL CHECK (reorder_level >= 0),
  supplier_fk bigint NOT NULL REFERENCES core.supplier (id),
  tags text[] NOT NULL DEFAULT '{}',
  unit_price numeric(12,2) NOT NULL CHECK (unit_price > 0.0),
  units_in_stock integer NOT NULL CHECK (units_in_stock >= 0),
  units_on_order integer NOT NULL CHECK (units_on_order >= 0),
  updated_at tracking_at
);
COMMENT ON TABLE core.product IS 'shortname: p';