
CREATE TABLE core.category
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_at tracking_at,
  last_modified_at tracking_at,
  color_hex text NOT NULL,
  color_is_light boolean NOT NULL,
  description text NOT NULL UNIQUE,
  entry_by tracking_by,
  last_modified_by tracking_by,
  name text NOT NULL UNIQUE
);
COMMENT ON TABLE core.category IS 'shortname: c_c';


CREATE TABLE core.supplier
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_fk bigint NOT NULL REFERENCES common.country (id),
  entry_at tracking_at,
  last_modified_at tracking_at,
  address text NOT NULL,
  city text NOT NULL,
  company_name text NOT NULL,
  contact_name text NOT NULL,
  contact_title text NOT NULL,
  entry_by tracking_by,
  last_modified_by tracking_by,
  phone text NOT NULL,
  postal_code text NOT NULL,
  state text NOT NULL,
  UNIQUE (country_fk, company_name)
);
COMMENT ON TABLE core.supplier IS 'shortname: c_s';


CREATE TABLE core.product
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_discontinued boolean NOT NULL,
  reorder_level integer NOT NULL CHECK (reorder_level >= 0),
  units_in_stock integer NOT NULL CHECK (units_in_stock >= 0),
  units_on_order integer NOT NULL CHECK (units_on_order >= 0),
  category_fk bigint NOT NULL REFERENCES core.category (id),
  supplier_fk bigint NOT NULL REFERENCES core.supplier (id),
  unit_price numeric(12,2) NOT NULL CHECK (unit_price > 0.0),
  entry_at tracking_at,
  last_modified_at tracking_at,
  entry_by tracking_by,
  last_modified_by tracking_by,
  name text NOT NULL UNIQUE,
  quantity_per_unit text NOT NULL,
  tags text[] NOT NULL DEFAULT '{}'
);
COMMENT ON TABLE core.product IS 'shortname: c_p';